dist: trusty
sudo: false

language: node_js
node_js:
  - "10"

branches:
  only:
  - master

addons:
  chrome: stable

cache:
  directories:
     - ./node_modules

install:
  - npm install


before_script:
  - npm install -g @angular/cli

script:
  - npm run test-headless
  - ng build --prod

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/hacker-news-clone
  on:
    branch: gh-pages
