dist: trusty
sudo: false
language: node_js
node_js:
- '10'

branches:
  only:
  - master

addons:
  chrome: stable

cache:
  directories:
  - "./node_modules"

install:
- npm install

before_script:
- npm install -g @angular/cli

script:
- npm run test-headless
- ng build --prod

deploy:
  provider: heroku
  skip_cleanup: true
  keep-history: true
  github_token: $GITHUB_TOKEN
  api_key:
    secure: lkASVt4SN9nlxjw8JFyVyPle9ObGcFWy8/Ip3utr5J7RoDs08qbt1+sw8KDAccK3AcMWrbjf1p/mwRMQNqu9YvRgCoSbnC01Qsyyflcridyh4deSGNEOn38HqJIojbch2gxI1WmFT56aneT2jAbh8GQgzankJWJRCeeYV8q4hw7MuG+XgthCKLWe9GJ1ORI2xwBkrhBUl82e1U3LyPLA6MH9+pbiDerE1upsUiEvN2/U8Q89mMOk6BdOXm23Yit+pNwJWFA2fY24I1x34J3hIWkpgT0IlQJi+bBjUUNQZ09IuqwLbR+hxn480keM7Qfmpj9J1cJACAQUFi3WUezVhaCuNtIm3AVbKz8UW0VNnA5cumjaF2i6z6hWn+TiBXPJYpHu4y9AmR/Fs0inIpJ4f6yvrb7jQdUYgZNlrvNDCmqtEhXF3b/72/v7FH/IsHulSnYIYAsjqPK0a/veTNZORtzAiC65AB2eAqjW1FvxTPbKRgKsgWSEoMcmNqHruXjcrBGrz1hSndY+wqovtiCUav/kLR8m9oyuwbnOkULliMtYwf3gRCPTQ4J3ZDhAqOz5+IGPEu6pr5sL4Cavkfd/zos0sb7j/aW04M35G8WZNNUqiYehvwbNWcHV9xVr+vR8bDyX84haKaDHMFXykaBHBQJt8kzlomLErGENIlFAPcU=
  app: hacker-news-clone
